{% set name = "espnet_model_zoo" %}
{% set version = "0.1.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/espnet_model_zoo-{{ version }}.tar.gz
  sha256: 61d88a1898d7d6bfebeb51100f194fa7fc9b68f959913255ee5ccf68090465b0

build:
  entry_points:
    - espnet_model_zoo_upload = espnet_model_zoo.zenodo_upload:main
    - espnet_model_zoo_download = espnet_model_zoo.downloader:cmd_download
    - espnet_model_zoo_query = espnet_model_zoo.downloader:cmd_query
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.6
    - pytest-runner
    - pip
  run:
    - python >=3.6
    - pandas
    - requests
    - tqdm
    - numpy
    - espnet
    - huggingface_hub
    - filelock

test:
  imports:
    - espnet_model_zoo
  commands:
    - pip check
    - espnet_model_zoo_upload --help
    - espnet_model_zoo_download --help
    - espnet_model_zoo_query --help
  requires:
    - pip

about:
  home: http://github.com/espnet/espnet_model_zoo
  summary: ESPnet Model Zoo
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - wietsedv
